### ISSUE TITLE
about the Text_ConvLSTM

### ISSUE THREAD

**Issue by BaiMeiyingxue** [PingCheng-Wei/DepressionEstimation#10]
Hi PingCheng-Wei,
I was curious why the Text_ConvLSTM doesn't have main_inference.py @.@

**Comment by PingCheng-Wei** [comment]
Hi BaiMeiyingxue,

Because during the single-modal experimental stage, the textual data doesn't show good performance. That's why there is no need to try out inference. It probably will be bad anyways. But the code idea should be pretty much similar to the main_inference.py in the other single-modal models

**Comment by BaiMeiyingxue** [comment]
I got it~ Thanks a lot!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ping-Cheng ***@***.***&gt;; 
发送时间: 2023年6月28日(星期三) 凌晨5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PingCheng-Wei/DepressionEstimation] about the Text_ConvLSTM (Issue #10)





 
Hi BaiMeiyingxue,
 
Because during the single-modal experimental stage, the textual data doesn't show good performance. That's why there is no need to try out inference. It probably will be bad anyways. But the code idea should be pretty much similar to the main_inference.py in the other single-modal models
