### ISSUE TITLE
About "ID_audio_trans.wav" file

### ISSUE THREAD

**Issue by W00ch** [PingCheng-Wei/DepressionEstimation#3]
Hi PingCheng,

I found a question in database_generation_v1:

How did I get the "ID_audio_trans.wav" file, and I didn't find any other handling of the audio in the code.

Best,

Wch

**Comment by PingCheng-Wei** [comment]
Hi Wch,

For this one, you have to manually convert the original audio files with some (online) tools to get the transgender voice. It is a bit hard to code some Python functions to realize this automatically because the principle of transforming the voice to another gender's voice is pretty complicated. But you can try if you want. I had tried before, but I only got an audio file with super strong background noise at the end.
