### ISSUE TITLE
About overcoming of a small-scale dataset

### ISSUE THREAD

**Issue by BaiMeiyingxue** [PingCheng-Wei/DepressionEstimation#5]
Hi PingCheng-Wei,
I read the document[https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/daic_woz_preprocessing/Chapter3_DepressionDataset.pdf](url) and the code, and I found increase the audio data, the  fkps_coor are needed, which is  computed  in _CLNF_features3D.txt. Could you give me some advice the function of the fkps_coor in audio dataset increase? Thanks!

**Comment by PingCheng-Wei** [comment]
Hi,
Sorry, I don't really understand your question. Can you please try to rephrase it? thank you
and sorry for the late reply. I don't check here that often.

**Comment by BaiMeiyingxue** [comment]
Hi PingCheng-Wei,
Sorry, I didn't make it clear. I wanna try the method [code](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/daic_woz_preprocessing/database_generation_v2/database_generation_train.py) to generate training data, but I don't have video data, in which the fkps_features are used this code 
```
def sliding_window(fkps_features, gaze_features, AUs_features, pose_features, 
                   hog_features, spectro, mel_spectro, text_feature, visual_sr, 
                   window_size, overlap_size, output_root, ID):

    
    frame_size = window_size * visual_sr
    hop_size = (window_size - overlap_size) * visual_sr
    num_frame = get_num_frame(fkps_features, frame_size, hop_size)

def get_num_frame(data, frame_size, hop_size):
    T = data.shape[0]
    if (T - frame_size) % hop_size == 0:
        num_frame = (T - frame_size) // hop_size + 1
    else:
        num_frame = (T - frame_size) // hop_size + 2
    return num_frame

```
If I've left something out or left something confusing or unexplained, I hope you'll let me know. Thanks!

**Comment by PingCheng-Wei** [comment]
Hi, 

Oh ~ I see. For your case, you just need to change the sliding window function a little bit like the input variable `fkps_features` for the function here `num_frame = get_num_frame(fkps_features, frame_size, hop_size)` and the `visual_sr`. Because what I was trying to do here at first is to get the `frame_size`, `hop_size`, and `num_frame`, which are essential parameters for the sliding window technique, and I realized this by utilizing the visual data as the base to align the timeline across different modalities. But if you don't need or have visual data. Then, you can just simply change the base to audio data, meaning that you use the `audio_sr` instead of `visual_sr` to get the `frame_size` and use `spectro` instead of `fkps_features` to get the `num_frame`.

**Comment by BaiMeiyingxue** [comment]
Hi PingCheng-Wei,
Thank you for your answer. Wishing you a pleasant holiday！
