### ISSUE TITLE
Problems with data generation

### ISSUE THREAD

**Issue by ccooo000** [PingCheng-Wei/DepressionEstimation#6]
hello,
Why are there more original_data than clipped_data?

**Comment by PingCheng-Wei** [comment]
Hi,
Because the clipped data includes only the clips where the participant is speaking/answering the questions. The rest of the clips where the interviewer asks questions or gives feedback is cut. That's why. the "clipped_data" here is in terms of how I pre-processed the data, especially audio, not in terms of the sliding window techniques, which will always be applied to both dataset at the end.
